name: Deliver Android App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: "setup application config"
        run: cp ./.github/config/google-services-dev.json ./android/app/google-services.json
      - uses: subosito/flutter-action@v1.1.1
        with:
          flutter-version: "1.12.13+hotfix.5"
      - run: flutter pub get
      - run: flutter build apk --debug -t lib/main.dart --build-name="latest build $(date +'%Y-%m-%d %H:%M')"
      - name: Deploy to DeployGate
        run: ./.github/scripts/deploy-android.sh
        env:
          DEPLOYGATE_API_KEY: ${{ secrets.DEPLOYGATE_API_KEY }}
      - name: Slack Notification
        uses: homoluctus/slatify@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: "Deliver to DeployGate"
          mention: "here"
          mention_if: "failure"
          channel: "#wyly-github"
          icon_emoji: "github"
          url: ${{ secrets.SLACK_WEBHOOK_URL }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
