name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1.1.1
        with:
          flutter-version: "1.12.13+hotfix.5"
      - run: flutter pub get
      - run: flutter test
      - run: flutter analyze
      - name: Slack Notification
        uses: homoluctus/slatify@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: "flutter test"
          mention: "here"
          mention_if: "failure"
          channel: "#wyly-github"
          icon_emoji: "github"
          url: ${{ secrets.SLACK_WEBHOOK_URL }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
